### ISSUE TITLE
PORT: Pypedal

### ISSUE THREAD

**Issue by samuelflock** [cs481-ekh/s24--1#82]
No User Story

Find a way to import the github Pypedal
Make sure the library works with Python3

**Comment by peterbusche** [comment]
[t:120] Tried on both windows and linux to get PyPedal library to install and run its test suit. Both failed. Tried to use 2to3 to convert old bits of code, and it still failed when trying to run tests. Went through all our source code files from Ziker, and grabbed any files from the pypedal library our source code is dependent on. Updated those files (pyp_classes and pyp_demog) to python3 along with all other depreciated library calls they had. Made sure when our source code uses them, they don't have any issues.

**Comment by peterbusche** [comment]
[t:240] Went through files orngMDS.py, pyp_metrics.py, pyp_newclasses.py, pyp_nrm.py, pyp_utils.py, and relate.py and updated all deprecated libraries and library calls. Commented out obsolete code that isnt used. Since python is interpreted and our code has alot of dynamic typing, alot of these errors could only be found by tracking error messages after running the code. However, I believe I got rid of most if not all issues from these files. Now, we only have to worry about getting our GUI (Descent.py) to effectively use these files.

**Comment by samuelflock** [comment]
{t:15}
